<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UpdatePhotoRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            //
            'original_password'=>'required',
            'new_password'=>'required',
            'repeat_password'=>'required|same:new_password'
        ];
    }
    public function messages(): array
    {
        return [
            'repeat_password.same'=>json_encode([
                'message' => 'repeat_password not same with password field',
                'code' => 422
            ])
        ];
//        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
